FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-chache-dir -r requirements.txt

EXPOSE 500
CMD ["mlflow", "server", "--host", "0.0.0.0", "--artifacts-destination", "/mlruns", "--workers", "1" ]