# docker-compose.yml
services:
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    networks:
      - mlflow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - GIT_PYTHON_REFRESH=quiet
    depends_on:
      mlflow-server:
        condition: service_healthy
    volumes:
      - ./mlruns:/mlruns
      - ./outputs:/app/outputs
    networks:
      - mlflow-network

networks:
  mlflow-network:
    driver: bridge