
services:
  mlflow_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow
      - POSTGRES_DB=mlflow
    volumes:
      - mlflow_db_data:/var/lib/postgresql/data
    networks:
      - mlflow_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow_server:
    image: mlflow_server
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_URI=postgresql+psycopg2://mlflow:mlflow@mlflow_db:5432/mlflow
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
    depends_on:
      mlflow_db:
        condition: service_healthy
    networks:
      - mlflow_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000 || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 60s

  wine_app:
    image: wine_quality_app
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
      - CONTAINER_APP_OUTPUT_DIR=/app/outputs
    volumes:
      - ./wine_outputs:/app/outputs
    depends_on:
      mlflow_server:
        condition: service_healthy
    networks:
      - mlflow_network

volumes:
  mlflow_db_data:
  mlflow_artifacts:

networks:
  mlflow_network:
    driver: bridge